.Dd April 1, 2021
.Dt BASE45 1
.Os
.Sh NAME
.Nm base45
.Nd command line base45 encoder and decoder
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Ar
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility will base45 encode or decode its
input
.Ar file ,
or standard input (if no file is specified) to the standard output or
to 
.Ar file
if an output file is also specified. Use the
.Fl d
flag to switch to decoding.
.Pp
The base45 format is designed to match the Alphanummeric set of Mode 2
or 0010 of ISO/IEC 18004 Qr codes.
.Pp
.Sh EXAMPLES
Translate the String
.Pa Hello
into base45:
.Pp
.Dl "echo -n Hello | base45"
.Sh HISTORY
This utiltiy was developed as part of the European Health Network
their Digital Green Certificate effort during the 2020-2021 COVID19
Crisis.
.Sh BUGS
Note that this utility is designed for the relatively modests strings that
are encoded into Qr barcodes; and hence does not have a nice streaming 
interface or similar.
.Sh STANDARDS
The
.Nm
utility conforms to ALPHANUMMERIC character set from section 7.44 of
ISO/EIC-18004. The actual set is 45 characters:
.Pp
.Dl 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:";
